package control

import (
	"context"
	"encoding/json"
	"errors"
	"fmt"
	"io"
	"net"
	"net/http"
	"net/url"
	"os"
	"strings"
	"time"
)

type RuntimeClient interface {
	Status(context.Context) (any, error)
	Reload(context.Context) error
}

type HTTPRuntimeClient struct {
	BaseURL string
	EnvFile string
	Client  *http.Client
}

func NewHTTPRuntimeClient(baseURL, envFile string) (*HTTPRuntimeClient, error) {
	baseURL = strings.TrimRight(strings.TrimSpace(baseURL), "/")
	parsed, err := url.Parse(baseURL)
	if err != nil || parsed.Scheme != "http" || parsed.Host == "" {
		return nil, errors.New("WAF admin URL must be an absolute HTTP URL")
	}
	host := parsed.Hostname()
	ip := net.ParseIP(host)
	if host != "localhost" && (ip == nil || !ip.IsLoopback()) {
		return nil, errors.New("WAF admin URL must use a loopback host")
	}
	transport := &http.Transport{Proxy: nil, DisableKeepAlives: true}
	return &HTTPRuntimeClient{
		BaseURL: baseURL, EnvFile: envFile,
		Client: &http.Client{Transport: transport, Timeout: 15 * time.Second},
	}, nil
}

func (c *HTTPRuntimeClient) Status(ctx context.Context) (any, error) {
	var result any
	if err := c.request(ctx, http.MethodGet, "/api/v1/status", &result); err != nil {
		return nil, err
	}
	return result, nil
}

func (c *HTTPRuntimeClient) Reload(ctx context.Context) error {
	var result any
	return c.request(ctx, http.MethodPost, "/api/v1/reload", &result)
}

func (c *HTTPRuntimeClient) request(ctx context.Context, method, path string, output any) error {
	token, err := readAdminToken(c.EnvFile)
	if err != nil {
		return err
	}
	req, err := http.NewRequestWithContext(ctx, method, c.BaseURL+path, nil)
	if err != nil {
		return err
	}
	req.Header.Set("Authorization", "Bearer "+token)
	resp, err := c.Client.Do(req)
	if err != nil {
		return err
	}
	defer resp.Body.Close()
	data, err := io.ReadAll(io.LimitReader(resp.Body, 2<<20))
	if err != nil {
		return err
	}
	if resp.StatusCode < 200 || resp.StatusCode >= 300 {
		var apiErr struct {
			Error string `json:"error"`
		}
		if json.Unmarshal(data, &apiErr) == nil && apiErr.Error != "" {
			return errors.New(apiErr.Error)
		}
		return fmt.Errorf("WAF admin API returned HTTP %d", resp.StatusCode)
	}
	if output != nil && len(data) > 0 {
		if err := json.Unmarshal(data, output); err != nil {
			return err
		}
	}
	return nil
}

func readAdminToken(path string) (string, error) {
	return readEnvironmentValue(path, "CHERRYWAF_ADMIN_TOKEN")
}

// ReadSetupToken returns the one-time first-boot claim code generated by the appliance.
func ReadSetupToken(path string) (string, error) {
	return readEnvironmentValue(path, "CHERRYWAF_SETUP_TOKEN")
}

func readEnvironmentValue(path, expectedKey string) (string, error) {
	data, err := os.ReadFile(path)
	if err != nil {
		return "", fmt.Errorf("read CherryWAF environment: %w", err)
	}
	for _, line := range strings.Split(string(data), "\n") {
		line = strings.TrimSpace(line)
		if line == "" || strings.HasPrefix(line, "#") {
			continue
		}
		key, value, ok := strings.Cut(line, "=")
		if strings.TrimSpace(key) != expectedKey || !ok {
			continue
		}
		value = strings.Trim(strings.TrimSpace(value), "\"'")
		if value == "" {
			break
		}
		return value, nil
	}
	return "", fmt.Errorf("%s is missing", expectedKey)
}
