    <section class="card"><header class="card-head"><div><h3>Network plan</h3><p>Changes roll back automatically unless confirmed.</p></div></header><div class="card-body"><form id="network-form">
      <div class="field"><label>Interface</label><select class="select" name="interface" ${!can("admin") ? "disabled" : ""}>${interfaces.map((item) => `<option value="${escapeAttr(item.name)}">${escapeHTML(item.name)} · ${escapeHTML((item.addresses || []).join(", ") || "unconfigured")}</option>`).join("")}</select></div>
      <label class="check"><input type="checkbox" name="dhcp4" checked ${!can("admin") ? "disabled" : ""}>Use IPv4 DHCP</label>
      <div class="field mt-16"><label>Static addresses (CIDR)</label><textarea class="textarea mono" name="addresses" placeholder="192.168.1.50/24" ${!can("admin") ? "disabled" : ""}></textarea></div>
      <div class="field-row"><div class="field"><label>Default gateway</label><input class="input mono" name="gateway4" placeholder="192.168.1.1" ${!can("admin") ? "disabled" : ""}></div><div class="field"><label>MTU</label><input class="input" type="number" min="576" max="9216" name="mtu" value="1500" ${!can("admin") ? "disabled" : ""}></div></div>
      <div class="field"><label>DNS servers</label><textarea class="textarea mono" name="nameservers" ${!can("admin") ? "disabled" : ""}>1.1.1.1\n8.8.8.8</textarea></div>
      ${can("admin") ? `<div class="form-actions"><button class="btn" type="button" id="validate-network">Preview Netplan</button><button class="btn btn-primary" type="submit" ${!result.helper_available || !interfaces.length ? "disabled" : ""}>Apply with rollback</button></div>` : ""}
    </form></div></section></div>`;
  const countdown = () => $$('[data-deadline]').forEach((item) => { const seconds = Math.max(0, Math.ceil((new Date(item.dataset.deadline).getTime() - Date.now()) / 1000)); item.textContent = seconds ? `${seconds}s to confirm` : "Rollback due"; }); countdown(); const timer = setInterval(countdown, 1000); setTimeout(() => clearInterval(timer), 65000);
  $$('[data-confirm-network]').forEach((button) => button.onclick = async () => { await api("/api/v1/network/confirm", { method: "POST", body: { token: button.dataset.confirmNetwork } }); toast("Network change confirmed."); await renderNetwork(content); });
  $$('[data-rollback-network]').forEach((button) => button.onclick = async () => { await api("/api/v1/network/rollback", { method: "POST", body: { token: button.dataset.rollbackNetwork } }); toast("Network configuration rolled back."); await renderNetwork(content); });
  if (can("admin")) {
    const form = $("#network-form"); const plan = () => { const values = new FormData(form); return { version: 1, interface: values.get("interface"), dhcp4: values.has("dhcp4"), addresses: listValue(values.get("addresses")), gateway4: String(values.get("gateway4") || "").trim(), nameservers: listValue(values.get("nameservers")), mtu: Number(values.get("mtu")) || 0 }; };
    $("#validate-network").onclick = async () => { try { const preview = await api("/api/v1/network/validate", { method: "POST", body: plan() }); openModal("Netplan preview", `<pre class="code-preview">${escapeHTML(preview.netplan)}</pre><div class="form-actions"><button class="btn" data-close-modal="true">Close</button></div>`); $$('[data-close-modal]', modalRoot).forEach((button) => button.onclick = closeModal); } catch (error) { toast(error.message, "error"); } };
    form.onsubmit = async (event) => { event.preventDefault(); if (!confirm("Apply this network plan? You must reconnect and confirm within 60 seconds or it will roll back automatically.")) return; try { const applied = await api("/api/v1/network/apply", { method: "POST", body: plan() }); toast(applied.message); await renderNetwork(content); } catch (error) { toast(error.message, "error"); } };
  }
}

async function renderRecovery(content) {
  content.innerHTML = page("Backup and rollback", "Create portable configuration backups or restore an automatically captured safety revision.", `<button class="btn btn-primary" id="create-backup">Create backup</button>`);
  const [backupResult, revisionResult] = await Promise.all([api("/api/v1/backups"), api("/api/v1/revisions")]); const backups = backupResult.backups || []; const revisions = revisionResult.revisions || [];
  $("#page-body").innerHTML = `<div class="notice">Backups include the WAF configuration and GUI rule file. Private keys, users, password hashes, audit events, and sessions are intentionally excluded.</div>
  <div class="grid two"><section class="card"><header class="card-head"><div><h3>Portable backups</h3><p>Manual ZIP snapshots stored on the appliance.</p></div></header><div class="table-wrap"><table><thead><tr><th>Created</th><th>Actor</th><th>Size</th><th></th></tr></thead><tbody>${backups.length ? backups.map((item) => `<tr><td><strong>${fmtDate(item.created_at)}</strong><div class="small muted mono">${escapeHTML(item.id)}</div></td><td>${escapeHTML(item.actor)}</td><td>${bytes(item.size)}</td><td><div class="actions"><a class="btn btn-sm" href="/api/v1/backups/${encodeURIComponent(item.id)}/download">Download</a><button class="btn btn-sm btn-success" data-restore-backup="${escapeAttr(item.id)}">Restore</button><button class="btn btn-sm btn-danger" data-delete-backup="${escapeAttr(item.id)}">Delete</button></div></td></tr>`).join("") : `<tr><td colspan="4"><div class="empty"><strong>No backups</strong>Create one before the next ambitious configuration experiment.</div></td></tr>`}</tbody></table></div></section>
  <section class="card"><header class="card-head"><div><h3>Safety revisions</h3><p>Captured automatically before every apply operation.</p></div></header><div class="table-wrap"><table><thead><tr><th>Created</th><th>Reason</th><th>Actor</th><th></th></tr></thead><tbody>${revisions.length ? revisions.map((item) => `<tr><td><strong>${fmtDate(item.created_at)}</strong><div class="small muted mono">${escapeHTML(item.id)}</div></td><td>${escapeHTML(item.reason)} ${item.restart_required ? statusBadge("Restart", "amber") : ""}</td><td>${escapeHTML(item.actor)}</td><td><button class="btn btn-sm btn-success" data-restore-revision="${escapeAttr(item.id)}">Restore</button></td></tr>`).join("") : `<tr><td colspan="4"><div class="empty">No safety revisions yet.</div></td></tr>`}</tbody></table></div></section></div>`;
  $("#create-backup").onclick = async () => { await api("/api/v1/backups", { method: "POST" }); toast("Backup created."); await renderRecovery(content); };
  $$('[data-restore-backup]').forEach((button) => button.onclick = async () => { if (!confirm("Restore this backup and reload the WAF?")) return; const result = await api(`/api/v1/backups/${encodeURIComponent(button.dataset.restoreBackup)}/restore`, { method: "POST" }); toast(result.result?.restart_required ? "Backup restored; restart required." : "Backup restored."); state.config = null; await renderRecovery(content); });
  $$('[data-delete-backup]').forEach((button) => button.onclick = async () => { if (!confirm("Delete this backup?")) return; await api(`/api/v1/backups/${encodeURIComponent(button.dataset.deleteBackup)}`, { method: "DELETE" }); toast("Backup deleted."); await renderRecovery(content); });
  $$('[data-restore-revision]').forEach((button) => button.onclick = async () => { if (!confirm("Restore this safety revision?")) return; const result = await api(`/api/v1/revisions/${encodeURIComponent(button.dataset.restoreRevision)}/restore`, { method: "POST" }); toast(result.restart_required ? "Revision restored; restart required." : "Revision restored."); state.config = null; await renderRecovery(content); });
}

async function renderUsers(content) {
  content.innerHTML = page("Users and roles", "Manage local Control Center identities and least-privilege access.", `<button class="btn btn-primary" id="add-user">Add user</button>`);
  const result = await api("/api/v1/users"); const users = result.users || [];
  $("#page-body").innerHTML = `<div class="card"><div class="table-wrap"><table><thead><tr><th>User</th><th>Role</th><th>Status</th><th>Last login</th><th>Updated</th><th></th></tr></thead><tbody>${users.map((user) => `<tr><td><strong>${escapeHTML(user.display_name)}</strong><div class="small muted mono">${escapeHTML(user.username)}</div></td><td>${statusBadge(user.role, user.role === "admin" ? "red" : user.role === "operator" ? "amber" : "blue")}</td><td>${user.disabled ? statusBadge("Disabled", "red") : statusBadge("Active", "green")}</td><td>${fmtDate(user.last_login_at)}</td><td>${fmtDate(user.updated_at)}</td><td><div class="actions"><button class="btn btn-sm" data-edit-user="${escapeAttr(user.id)}">Edit</button>${user.id !== state.user.id ? `<button class="btn btn-sm btn-danger" data-delete-user="${escapeAttr(user.id)}">Delete</button>` : ""}</div></td></tr>`).join("")}</tbody></table></div></div>`;
  $("#add-user").onclick = () => openUserEditor(null, users);
